# Generated by Django 4.2.20 on 2025-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jusik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('company_code', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
    ]
