# Generated by Django 4.2.20 on 2025-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jusik',
            old_name='copany_code',
            new_name='company_code',
        ),
        migrations.AlterField(
            model_name='jusik',
            name='created_at',
            field=models.CharField(max_length=50),
        ),
    ]
